baseURL = 'https://hnolzen.github.io/almuth-art/'
languageCode = 'de'
title = 'Almuth Minich'
theme = 'eternity'
enableEmoji = true

[params]
title = "Almuth Art"
author = "hnolzen"
description = "Website of Almuth Minich"

  [[params.socials]]
      icon = 'far fa-envelope fa-lg'
      url = 'mailto: '
      landing = true
