baseURL = 'https://hnolzen.github.io/almuth-art/'
languageCode = 'de'
title = 'Almuth Minich'
subtitle = 'Kunst aus dem Emsland'
theme = 'eternity'
enableEmoji = true

[params]
title = "Almuth Minich"
author = "Almuth Minich"
description = "Almuth Minich"

copyright = 'Alle Rechte vorbehalten.'

homepage = "/welcome/"
bypassWelcomePage = true

[portfolio.columns.desktop]
welcome = 4
natur = 3
default = 4

[portfolio.columns.mobile]
default = 2

[[params.socials]]
icon = 'far fa-envelope fa-lg'
url = 'mailto:almuth.minich@posteo.de'
landing = true

specialPages = ['welcome']

disableRadius = false
moveIt = false
disableAlwaysResize = false

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
    name = 'willkommen'
    url = '/welcome/'
    weight = 1

[[menu.main]]
	name = 'werke'
    url = '/tags/werke/'
    weight = 2

[[menu.main]]
    name = 'abstrakt'
    url = '/tags/abstrakt/'
    weight = 3

[[menu.main]]
    name = 'natur'
    url = '/tags/natur/'
    weight = 4
	
[[menu.main]]
    name = 'über'
    url = '/about/'
    weight = 5
